const {
  sequelize,
} = require('../config/database.config');
const Sequelize = require('sequelize');

const Person = sequelize.define('census_learn_sql', {
  age: Sequelize.INTEGER,
  'class of worker': Sequelize.STRING,
  'industry code': Sequelize.STRING,
  'occupation code': Sequelize.STRING,
  education: Sequelize.STRING,
  'wage per hour': Sequelize.STRING,
  'last education': Sequelize.STRING,
  'marital status': Sequelize.STRING,
  'major industry code': Sequelize.STRING,
  'major occupation code': Sequelize.STRING,
  mace: Sequelize.STRING,
  hispanice: Sequelize.STRING,
  sex: Sequelize.STRING,
  'member of labor': Sequelize.STRING,
  'reason for unemployment': Sequelize.STRING,
  fulltime: Sequelize.STRING,
  'capital gain': Sequelize.STRING,
  'capital loss': Sequelize.STRING,
  dividends: Sequelize.STRING,
  'income tax liability': Sequelize.STRING,
  'previous residence region': Sequelize.STRING,
  'previous residence state': Sequelize.STRING,
  'household-with-family': Sequelize.STRING,
  'household-simple': Sequelize.STRING,
  weight: Sequelize.STRING,
  'msa-change': Sequelize.STRING,
  'reg-change': Sequelize.STRING,
  'within-reg-change': Sequelize.STRING,
  'lived-here': Sequelize.STRING,
  'migration prev res in sunbelt': Sequelize.STRING,
  w: Sequelize.STRING,
  'family members under 118': Sequelize.STRING,
  'father birth country': Sequelize.STRING,
  'mother birth country': Sequelize.STRING,
  'birth country': Sequelize.STRING,
  citizenship: Sequelize.STRING,
  'own business or self employed': Sequelize.STRING,
  "fill questionnaire for veteran's admin": Sequelize.STRING,
  'veterans benefits': Sequelize.STRING,
  'weeks worked in year': Sequelize.STRING,
  year: Sequelize.STRING,
  'salary range': Sequelize.STRING,
});

exports.Person = Person;
